//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

namespace Ild_Music.Assets 
{
       
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources 
    {    
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() 
        {}
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ild-Music.Assets.Languages.Resources", Assembly.GetExecutingAssembly());
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SearchBarWatermark => ResourceManager.GetString("SearchBarWatermark", resourceCulture);
 
        public static string HomeNavbarItem => ResourceManager.GetString("HomeNavbarItem", resourceCulture);
 
        public static string ListNavbarItem => ResourceManager.GetString("ListNavbarItem", resourceCulture);
 
        public static string BrowseNavbarItem => ResourceManager.GetString("BrowseNavbarItem", resourceCulture);

        public static string ArtistLabelStartView => ResourceManager.GetString("ArtistLabelStartView", resourceCulture);
 
        public static string PlaylistLabelStartView => ResourceManager.GetString("PlaylistLabelStartView", resourceCulture);
 
        public static string TrackLabelStartView => ResourceManager.GetString("TrackLabelStartView", resourceCulture);
 
    }
}